# Data Mining Techniques
## Assignment 3
### Question 4

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.set_printoptions(suppress=True, precision=3)

4a)

# Case Study 1: [Sentiment Analysis on movie reviews](https://github.com/scikit-learn/scikit-learn/tree/master/doc/tutorial/text_analytics/solutions/exercise_02_sentiment.py) <a class="anchor" id="S3"></a> 

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_files
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression


In [ ]:
df = pd.read_csv("Churn_Modelling.csv", index_col=[1])
del df['RowNumber']
del df['Surname']

df.Gender[df.Gender == 'Male'] = 1
df.Gender[df.Gender == 'Female'] = 0

expl = ['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
x = df[expl]
y = df[['Exited']]

Split the dataset in training and test set

In [10]:
docs_train, docs_test, y_train, y_test = train_test_split(
    dataset.data, dataset.target, test_size=0.25, random_state=None)

print("A positive sample:\n")
print(y_train[10], docs_train[10][:1000])

A positive sample:

0 b"woody allen is one of the most successful artist-directors in hollywood , but he is becoming less and less reliable as a filmmaker . \nin his early years of film-making he mastered the simple comedy . \nfrom there he went into a second phase and took risks experimenting with different approaches and styles . \nsome of these work better than others . \nzelig and crimes and misdemeanors are the work of a creative and intelligent artist . \ndeconstructing harry goes to the other extreme and is a bizarre experiment demanding more of the viewer than it gives back . \nharry block ( allen ) has in his life only two drives . \nhe wants to have sex with as many women as possible and when he makes a mess of his life and those of his lovers he wants to retreat into his writing . \nthe story of this static and highly unsympathetic character is told with a number of often clumsy stylistic experiments . \nperhaps the most irritating device is to express the disjointedness of 

In [11]:
print("A negative sample:\n")
print(y_train[50], docs_train[50][:1000])

A negative sample:

1 b'the thirteenth floor , the third in what i would call " the reality check movie series " , is very similar to the other reality check movies released this year , the matrix and existenz . \nall three made you think , made you wonder what is real , what isn\'t , and if our world is just a huge game . \nthe thirteenth floor doesn\'t reach the level of originality , creativity , and curiosity sparked by the matrix and existenz , but it certainly gives a great shot at it . \nin the matrix , we were told that the humans are simply a virus . \nin existenz , we learned that our life could be just a game . \nin the thirteenth floor , we learn that we are just electronic devices , living under another world of electronic devices . \nthere is just one world on top of another , and everything in them are fake and electronically generated . \nthe thirteenth floor took a huge , risky turn that i didn\'t expect it to take , and i\'m not very sure it was such a great turn to m

Build a SVC model

In [12]:
pipeline = Pipeline([
    ('vect', TfidfVectorizer(min_df=3, max_df=0.95)),
    ('clf', LinearSVC(C=1000)),
])

parameters = {
    'vect__ngram_range': [(1, 1), (1, 2)],
}
grid_search = GridSearchCV(pipeline, parameters, n_jobs=-1)
grid_search.fit(docs_train, y_train)

n_candidates = len(grid_search.cv_results_['params'])
for i in range(n_candidates):
    print(i, 'params - %s; mean - %0.2f; std - %0.2f'
             % (grid_search.cv_results_['params'][i],
                grid_search.cv_results_['mean_test_score'][i],
                grid_search.cv_results_['std_test_score'][i]))

y_predicted = grid_search.predict(docs_test)

C:\Users\michi\Anaconda3\envs\tfenv\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\michi\Anaconda3\envs\tfenv\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0 params - {'vect__ngram_range': (1, 1)}; mean - 0.83; std - 0.01
1 params - {'vect__ngram_range': (1, 2)}; mean - 0.85; std - 0.01


In [13]:
print(metrics.classification_report(y_test, y_predicted, target_names=dataset.target_names))

              precision    recall  f1-score   support

         neg       0.86      0.89      0.87       240
         pos       0.89      0.86      0.88       260

    accuracy                           0.87       500
   macro avg       0.87      0.87      0.87       500
weighted avg       0.87      0.87      0.87       500



In [14]:
print(metrics.confusion_matrix(y_test, y_predicted))

[[213  27]
 [ 36 224]]


4b)

In [16]:
pipeline = Pipeline([
    ('vect', TfidfVectorizer(min_df=3, max_df=0.95)),
    ('dtc', DecisionTreeClassifier()),
])

parameters = {
    'vect__ngram_range': [(1, 1), (1, 2)],
}
grid_search = GridSearchCV(pipeline, parameters, n_jobs=-1)
grid_search.fit(docs_train, y_train)

n_candidates = len(grid_search.cv_results_['params'])
for i in range(n_candidates):
    print(i, 'params - %s; mean - %0.2f; std - %0.2f'
             % (grid_search.cv_results_['params'][i],
                grid_search.cv_results_['mean_test_score'][i],
                grid_search.cv_results_['std_test_score'][i]))

y_predicted = grid_search.predict(docs_test)

C:\Users\michi\Anaconda3\envs\tfenv\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0 params - {'vect__ngram_range': (1, 1)}; mean - 0.62; std - 0.00
1 params - {'vect__ngram_range': (1, 2)}; mean - 0.61; std - 0.01


In [17]:
print(metrics.classification_report(y_test, y_predicted, target_names=dataset.target_names))

              precision    recall  f1-score   support

         neg       0.61      0.65      0.63       240
         pos       0.66      0.62      0.64       260

    accuracy                           0.64       500
   macro avg       0.64      0.64      0.64       500
weighted avg       0.64      0.64      0.64       500



In [18]:
print(metrics.confusion_matrix(y_test, y_predicted))

[[156  84]
 [ 98 162]]


The performance has become worse compared to a), because there are less True positives and negatives.

4c)

In [19]:
pipeline = Pipeline([
    ('vect', TfidfVectorizer(min_df=3, max_df=0.95)),
    ('lr', LogisticRegression()),
])

parameters = {
    'vect__ngram_range': [(1, 1), (1, 2)],
}
grid_search = GridSearchCV(pipeline, parameters, n_jobs=-1)
grid_search.fit(docs_train, y_train)

n_candidates = len(grid_search.cv_results_['params'])
for i in range(n_candidates):
    print(i, 'params - %s; mean - %0.2f; std - %0.2f'
             % (grid_search.cv_results_['params'][i],
                grid_search.cv_results_['mean_test_score'][i],
                grid_search.cv_results_['std_test_score'][i]))

y_predicted = grid_search.predict(docs_test)

C:\Users\michi\Anaconda3\envs\tfenv\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\michi\Anaconda3\envs\tfenv\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0 params - {'vect__ngram_range': (1, 1)}; mean - 0.82; std - 0.02
1 params - {'vect__ngram_range': (1, 2)}; mean - 0.83; std - 0.01


In [20]:
print(metrics.classification_report(y_test, y_predicted, target_names=dataset.target_names))

              precision    recall  f1-score   support

         neg       0.80      0.89      0.84       240
         pos       0.89      0.79      0.84       260

    accuracy                           0.84       500
   macro avg       0.84      0.84      0.84       500
weighted avg       0.85      0.84      0.84       500



In [21]:
print(metrics.confusion_matrix(y_test, y_predicted))

[[214  26]
 [ 54 206]]


The performance has improved compared to b), because there are more True positives and negatives.